using System.Text;

namespace NetAgents.Lockfile;

public static class LockfileWriter
{
    private const string Header = "# Auto-generated by netagents. Do not edit.\n";

    public static async Task WriteAsync(string filePath, LockfileData lockfile, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.AppendLine($"version = {lockfile.Version}");

        foreach (var name in lockfile.Skills.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            sb.AppendLine();
            sb.AppendLine($"[skills.{name}]");
            AppendSkillFields(sb, lockfile.Skills[name]);
        }

        var content = sb.ToString().TrimEnd() + "\n";
        await File.WriteAllTextAsync(filePath, content, Encoding.UTF8, ct).ConfigureAwait(false);
    }

    private static void AppendSkillFields(StringBuilder sb, LockedSkill skill)
    {
        switch (skill)
        {
            case LockedGitSkill g:
                sb.AppendLine($"source = \"{Escape(g.Source)}\"");
                sb.AppendLine($"resolved_url = \"{Escape(g.ResolvedUrl)}\"");
                sb.AppendLine($"resolved_path = \"{Escape(g.ResolvedPath)}\"");
                if (g.ResolvedRef is not null)
                    sb.AppendLine($"resolved_ref = \"{Escape(g.ResolvedRef)}\"");
                break;
            case LockedLocalSkill l:
                sb.AppendLine($"source = \"{Escape(l.Source)}\"");
                break;
        }
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
