namespace NetAgents.Gitignore;

public static class GitignoreWriter
{
    private const string Header = """
        # Auto-generated by netagents. Do not edit.
        # Managed skills (installed by netagents)
        """;

    private static readonly string[] RootGitignoreEntries = ["agents.lock", ".agents/.gitignore"];

    private const string RootGitignoreComment = "# Auto-generated by netagents — do not commit these files.";

    /// <summary>
    /// Generate .agents/.gitignore listing managed skill directories.
    /// </summary>
    public static async Task WriteAgentsGitignoreAsync(
        string agentsDir,
        IReadOnlyList<string> managedSkillNames,
        CancellationToken ct = default)
    {
        var lines = new List<string> { Header };
        foreach (var name in managedSkillNames.OrderBy(n => n, StringComparer.Ordinal))
        {
            lines.Add($"/skills/{name}/");
        }
        lines.Add(""); // trailing newline

        await File.WriteAllTextAsync(
            Path.Combine(agentsDir, ".gitignore"),
            string.Join("\n", lines),
            ct).ConfigureAwait(false);
    }

    /// <summary>
    /// Check which root .gitignore entries are missing.
    /// Returns the list of entries not present (empty if all present).
    /// </summary>
    public static async Task<IReadOnlyList<string>> CheckRootGitignoreEntriesAsync(
        string projectRoot,
        CancellationToken ct = default)
    {
        var gitignorePath = Path.Combine(projectRoot, ".gitignore");

        var content = "";
        if (File.Exists(gitignorePath))
            content = await File.ReadAllTextAsync(gitignorePath, ct).ConfigureAwait(false);

        var lines = new HashSet<string>(content.Split('\n').Select(l => l.Trim()));
        var missing = new List<string>();
        foreach (var entry in RootGitignoreEntries)
        {
            if (!lines.Contains(entry))
                missing.Add(entry);
        }

        return missing;
    }

    /// <summary>
    /// Ensure the root .gitignore contains entries for agents.lock and .agents/.gitignore.
    /// Writes missing entries. Returns the list of entries that were added.
    /// </summary>
    public static async Task<IReadOnlyList<string>> EnsureRootGitignoreEntriesAsync(
        string projectRoot,
        CancellationToken ct = default)
    {
        var gitignorePath = Path.Combine(projectRoot, ".gitignore");
        var missing = await CheckRootGitignoreEntriesAsync(projectRoot, ct).ConfigureAwait(false);

        if (missing.Count == 0)
            return [];

        var content = "";
        if (File.Exists(gitignorePath))
            content = await File.ReadAllTextAsync(gitignorePath, ct).ConfigureAwait(false);

        var suffix = content.Length > 0 && !content.EndsWith('\n') ? "\n" : "";
        var block = $"{RootGitignoreComment}\n{string.Join("\n", missing)}\n";
        await File.WriteAllTextAsync(gitignorePath, $"{content}{suffix}{block}", ct).ConfigureAwait(false);

        return missing;
    }
}
