namespace NetAgents.Tests.Gitignore;

using AwesomeAssertions;
using NetAgents.Gitignore;
using Xunit;

public class WriteAgentsGitignoreTests : IAsyncLifetime
{
    private string _dir = null!;

    public async ValueTask InitializeAsync()
    {
        _dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(Path.Combine(_dir, ".agents"));
        await ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, true);
        await ValueTask.CompletedTask;
    }

    [Fact]
    public async Task WritesHeaderWithNoManagedSkills()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, [], TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"),
            TestContext.Current.CancellationToken);
        content.Should().Contain("Auto-generated by netagents");
        content.Split('\n').Should().NotContain(l => l.StartsWith("/skills/"));
    }

    [Fact]
    public async Task ListsManagedSkillDirectories()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["pdf", "find-bugs", "code-review"],
            TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"),
            TestContext.Current.CancellationToken);
        content.Should().Contain("/skills/code-review/");
        content.Should().Contain("/skills/find-bugs/");
        content.Should().Contain("/skills/pdf/");
    }

    [Fact]
    public async Task SortsSkillNamesAlphabetically()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["zebra", "alpha", "middle"],
            TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"),
            TestContext.Current.CancellationToken);
        var lines = content.Split('\n').Where(l => l.StartsWith("/skills/")).ToArray();
        lines.Should().BeEquivalentTo(
            ["/skills/alpha/", "/skills/middle/", "/skills/zebra/"]);
    }

    [Fact]
    public async Task OverwritesExistingGitignore()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["old-skill"],
            TestContext.Current.CancellationToken);
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["new-skill"],
            TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"),
            TestContext.Current.CancellationToken);
        content.Should().NotContain("old-skill");
        content.Should().Contain("new-skill");
    }
}

public class CheckRootGitignoreEntriesTests : IAsyncLifetime
{
    private string _dir = null!;

    public async ValueTask InitializeAsync()
    {
        _dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(_dir);
        await ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, true);
        await ValueTask.CompletedTask;
    }

    [Fact]
    public async Task ReturnsAllEntriesWhenNoGitignoreExists()
    {
        var missing = await GitignoreWriter.CheckRootGitignoreEntriesAsync(_dir, TestContext.Current.CancellationToken);
        missing.Should().Contain("agents.lock");
        missing.Should().Contain(".agents/.gitignore");
    }

    [Fact]
    public async Task ReturnsMissingEntries()
    {
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "agents.lock\n",
            TestContext.Current.CancellationToken);
        var missing = await GitignoreWriter.CheckRootGitignoreEntriesAsync(_dir, TestContext.Current.CancellationToken);
        missing.Should().BeEquivalentTo([".agents/.gitignore"]);
    }

    [Fact]
    public async Task ReturnsEmptyWhenAllEntriesPresent()
    {
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "agents.lock\n.agents/.gitignore\n",
            TestContext.Current.CancellationToken);
        var missing = await GitignoreWriter.CheckRootGitignoreEntriesAsync(_dir, TestContext.Current.CancellationToken);
        missing.Should().BeEmpty();
    }
}

public class EnsureRootGitignoreEntriesTests : IAsyncLifetime
{
    private string _dir = null!;

    public async ValueTask InitializeAsync()
    {
        _dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(_dir);
        await ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, true);
        await ValueTask.CompletedTask;
    }

    [Fact]
    public async Task CreatesGitignoreWithEntriesWhenMissing()
    {
        var ct = TestContext.Current.CancellationToken;
        var added = await GitignoreWriter.EnsureRootGitignoreEntriesAsync(_dir, ct);
        added.Should().Contain("agents.lock");
        added.Should().Contain(".agents/.gitignore");

        var content = await File.ReadAllTextAsync(Path.Combine(_dir, ".gitignore"), ct);
        content.Should().Contain("agents.lock");
        content.Should().Contain(".agents/.gitignore");
    }

    [Fact]
    public async Task AppendsMissingEntriesToExistingGitignore()
    {
        var ct = TestContext.Current.CancellationToken;
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "node_modules/\n", ct);
        await GitignoreWriter.EnsureRootGitignoreEntriesAsync(_dir, ct);

        var content = await File.ReadAllTextAsync(Path.Combine(_dir, ".gitignore"), ct);
        content.Should().Contain("node_modules/");
        content.Should().Contain("agents.lock");
    }

    [Fact]
    public async Task IsNoOpWhenEntriesAlreadyPresent()
    {
        var ct = TestContext.Current.CancellationToken;
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "agents.lock\n.agents/.gitignore\n", ct);
        var added = await GitignoreWriter.EnsureRootGitignoreEntriesAsync(_dir, ct);
        added.Should().BeEmpty();
    }
}
