using NetAgents.Gitignore;
using Xunit;

namespace NetAgents.Tests.Gitignore;

// ── WriteAgentsGitignoreAsync ────────────────────────────────────────────────

public class WriteAgentsGitignoreTests : IAsyncLifetime
{
    private string _dir = null!;

    public async ValueTask InitializeAsync()
    {
        _dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(Path.Combine(_dir, ".agents"));
        await ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, recursive: true);
        await ValueTask.CompletedTask;
    }

    [Fact]
    public async Task WritesHeaderWithNoManagedSkills()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, [], TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"), TestContext.Current.CancellationToken);
        Assert.Contains("Auto-generated by netagents", content);
        Assert.DoesNotContain(content.Split('\n'), l => l.StartsWith("/skills/"));
    }

    [Fact]
    public async Task ListsManagedSkillDirectories()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["pdf", "find-bugs", "code-review"], TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"), TestContext.Current.CancellationToken);
        Assert.Contains("/skills/code-review/", content);
        Assert.Contains("/skills/find-bugs/", content);
        Assert.Contains("/skills/pdf/", content);
    }

    [Fact]
    public async Task SortsSkillNamesAlphabetically()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["zebra", "alpha", "middle"], TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"), TestContext.Current.CancellationToken);
        var lines = content.Split('\n').Where(l => l.StartsWith("/skills/")).ToArray();
        Assert.Equal(
            ["/skills/alpha/", "/skills/middle/", "/skills/zebra/"],
            lines);
    }

    [Fact]
    public async Task OverwritesExistingGitignore()
    {
        var agentsDir = Path.Combine(_dir, ".agents");
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["old-skill"], TestContext.Current.CancellationToken);
        await GitignoreWriter.WriteAgentsGitignoreAsync(agentsDir, ["new-skill"], TestContext.Current.CancellationToken);

        var content = await File.ReadAllTextAsync(Path.Combine(agentsDir, ".gitignore"), TestContext.Current.CancellationToken);
        Assert.DoesNotContain("old-skill", content);
        Assert.Contains("new-skill", content);
    }
}

// ── CheckRootGitignoreEntriesAsync ───────────────────────────────────────────

public class CheckRootGitignoreEntriesTests : IAsyncLifetime
{
    private string _dir = null!;

    public async ValueTask InitializeAsync()
    {
        _dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(_dir);
        await ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, recursive: true);
        await ValueTask.CompletedTask;
    }

    [Fact]
    public async Task ReturnsAllEntriesWhenNoGitignoreExists()
    {
        var missing = await GitignoreWriter.CheckRootGitignoreEntriesAsync(_dir, TestContext.Current.CancellationToken);
        Assert.Contains("agents.lock", missing);
        Assert.Contains(".agents/.gitignore", missing);
    }

    [Fact]
    public async Task ReturnsMissingEntries()
    {
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "agents.lock\n", TestContext.Current.CancellationToken);
        var missing = await GitignoreWriter.CheckRootGitignoreEntriesAsync(_dir, TestContext.Current.CancellationToken);
        Assert.Equal([".agents/.gitignore"], missing);
    }

    [Fact]
    public async Task ReturnsEmptyWhenAllEntriesPresent()
    {
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "agents.lock\n.agents/.gitignore\n", TestContext.Current.CancellationToken);
        var missing = await GitignoreWriter.CheckRootGitignoreEntriesAsync(_dir, TestContext.Current.CancellationToken);
        Assert.Empty(missing);
    }
}

// ── EnsureRootGitignoreEntriesAsync ──────────────────────────────────────────

public class EnsureRootGitignoreEntriesTests : IAsyncLifetime
{
    private string _dir = null!;

    public async ValueTask InitializeAsync()
    {
        _dir = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        Directory.CreateDirectory(_dir);
        await ValueTask.CompletedTask;
    }

    public async ValueTask DisposeAsync()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, recursive: true);
        await ValueTask.CompletedTask;
    }

    [Fact]
    public async Task CreatesGitignoreWithEntriesWhenMissing()
    {
        var ct = TestContext.Current.CancellationToken;
        var added = await GitignoreWriter.EnsureRootGitignoreEntriesAsync(_dir, ct);
        Assert.Contains("agents.lock", added);
        Assert.Contains(".agents/.gitignore", added);

        var content = await File.ReadAllTextAsync(Path.Combine(_dir, ".gitignore"), ct);
        Assert.Contains("agents.lock", content);
        Assert.Contains(".agents/.gitignore", content);
    }

    [Fact]
    public async Task AppendsMissingEntriesToExistingGitignore()
    {
        var ct = TestContext.Current.CancellationToken;
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "node_modules/\n", ct);
        await GitignoreWriter.EnsureRootGitignoreEntriesAsync(_dir, ct);

        var content = await File.ReadAllTextAsync(Path.Combine(_dir, ".gitignore"), ct);
        Assert.Contains("node_modules/", content);
        Assert.Contains("agents.lock", content);
    }

    [Fact]
    public async Task IsNoOpWhenEntriesAlreadyPresent()
    {
        var ct = TestContext.Current.CancellationToken;
        await File.WriteAllTextAsync(Path.Combine(_dir, ".gitignore"), "agents.lock\n.agents/.gitignore\n", ct);
        var added = await GitignoreWriter.EnsureRootGitignoreEntriesAsync(_dir, ct);
        Assert.Empty(added);
    }
}
